### ISSUE TITLE
"Error: EPERM: operation not permitted, lstat" on device watch with NativeScript version 2.5.3

### ISSUE THREAD

**Issue by briosheje** [NativeScript/nativescript-vscode-extension#122]
I had no issue with version 2.5.2, after updating I get an lstat error everytime I perform a change in any file, I need to delete the platforms/android/src/main directory to make it work again (and, after the first change, the same error pops up again):

Stack:
```
Error: EPERM: operation not permitted, lstat 'c:\Users\briosheje\Documents\vierinc_handler\NativeScript\TestApp\platforms\android\src\main\assets\app\item\item-detail.component.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at rmdirSyncRecursive (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\rm.js:28:23)
    at C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\rm.js:136:9
    at Array.forEach (native)
    at Object._rm (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\rm.js:113:9)
    at Object.rm (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\common.js:365:25)
    at FileSystem.deleteDirectory (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:101:17)
    at AppFilesUpdater.deleteDestinationItem (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\lib\services\app-files-updater.js:38:17)
    at _.each (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\lib\services\app-files-updater.js:26:18)
```

Permissions on folders are ok already, so not sure what the issue is really, but since this last update I'm having troubles with the extension.

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/nativescript-cli#2680
