### ISSUE TITLE
Livesync dies after a few minutes

### ISSUE THREAD

**Issue by dwichelo** [NativeScript/nativescript-vscode-extension#126]
I'm currently running Nativescript in combination with visual studio code. 
After a few minutes my emulator will no longer pick up changes and the following error is thrown:

`Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)
[NSDebugAdapter] The tns command finished its execution with code 0.`

For reference: 
I'm using a clean install of visual studio code v1.11.1 windows + extension (ext install nativescript).
My app is a new unalterd javascript project (tns create testProject)
The emulator is started via launch.json, which is freshly generated by nativescript:

> {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch on iOS",
            "type": "nativescript",
            "request": "launch",
            "platform": "ios",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        },
        {
            "name": "Attach on iOS",
            "type": "nativescript",
            "request": "attach",
            "platform": "ios",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": false
        },
        {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        },
        {
            "name": "Attach on Android",
            "type": "nativescript",
            "request": "attach",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": false
        }
    ]
}

What is going wrong here?

**Comment by pkoleva** [comment]
Hey, @dwichelo,

Can you tell us which CLI version you've installed and the version of the NS extension?
Also if they are not the latest you can try upgrading and check if the issue is valid with the latest bits as well.

Thanks!

**Comment by Plamen5kov** [comment]
Closing due to inactivity.
