### ISSUE TITLE
debugging not working

### ISSUE THREAD

**Issue by georgejecook** [NativeScript/nativescript-vscode-extension#17]
set my breakpoints, run the app I get this in the output

Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:749:11)
    at Socket.Readable.resume (_stream_readable.js:734:3)
    at /usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:93:32
    at Socket.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/helpers.js:254:13)
    at Socket.emit (events.js:92:17)
    at Object.afterConnect [as oncomplete] (net.js:887:10)

**Comment by georgejecook** [comment]
ok. had node010 installed. installing default brew version of node resolved the issue for me.
