### ISSUE TITLE
Breakpoint not hit with launch options in OSX but attach

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-vscode-extension#207]
_From @DavoBR on September 14, 2018 1:18_

**tns doctor result:**

DAVID-MAC:~ davo$ tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.2.3 version and is up to date.

VSCode version: 1.27.2

**Symptoms:**

1.  Breakpoint not hit when a i choose "Launch on iOS" options to start debug but work when i choose "Attach on iOS" 

2. I get this when start debug in VSCode

Traceback (most recent call last):

  File "<input>", line 1, in <module>

  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref

  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (

ImportError: cannot import name _remove_dead_weakref

TypeError: Cannot set property 'deviceIdentifier' of undefined
    at SocketProxyFactory.<anonymous> (/Users/davo/.nvm/versions/node/v10.10.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:88:46)
    at Generator.throw (<anonymous>)
    at rejected (/Users/davo/.nvm/versions/node/v10.10.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)

 

_Copied from original issue: NativeScript/NativeScript#6265_

**Comment by tsonevn** [comment]
Hi @DavoBR,
Can you check if you are using the latest version of nativescript vs code extension - `0.8.1`? Also, does this happen when deploying the app on a device or on a simulator? 
I tested the VSCode debugging with `Launch on iOS` option and the project stopped on the breakpoint.

**Comment by DanHef** [comment]
Hi @tsonevn,

I am having the same issue. For me I have the newest code extension installed (0.8.1) and tried it with the latest nativescript version (4.2.4) and the nativescript RC 4.2.4-2018-09-17-12236. I used node version 10.11.0. For me it happens when deploying on a simulator, didn't have the chance to try deploying it to a device in this setup yet.

**Comment by tsonevn** [comment]
Hi @racknoris,
Can you try restarting the device and simulator, that you are using for debugging then start again the `tns debug ios` command?

**Comment by JonLevy** [comment]
`tns debug ios` is working for me, but not the VSCode extension.

When trying to use the extension, the debugger fails to attach.  Here is a sample output:

`[NSDebugAdapter] Running tns command...

[NativeScriptCli] execute: tns --analyticsClient VSCode debug ios --watch --debug-brk 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token

Searching for devices...

Found peer TypeScript 3.1.6

Skipping prepare.

Successfully transferred all files on device 35B23925-5E95-4252-A292-525229B27EE5.

Restarting application on device 35B23925-5E95-4252-A292-525229B27EE5...

org.nativescript.roilApp: org.nativescript.roilApp: 3504


Setting up debugger proxy...
Press Ctrl + C to terminate, or disconnect.


Opened localhost 41002

To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:41002


Successfully synced application org.nativescript.roilApp on device 35B23925-5E95-4252-A292-525229B27EE5.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

[NSDebugAdapter] Ready to attach to application on 41002

Frontend client connected.

NativeScript debugger has opened inspector socket on port 18183 for org.nativescript.roilApp.

NativeScript waiting for debugger.

Cannot connect to device socket. The error message is 'Timeout while waiting for lock "/Users/jonathanlevy/.local/share/.nativescript-cli/54989e3d05a7e989423bfa34a89660c2"'.`
