### ISSUE TITLE
Debugger not connecting to simulator

### ISSUE THREAD

**Issue by faustinoribeiro** [NativeScript/nativescript-vscode-extension#43]
I installed the extension in VS Code 0.10.11 (Windows 10).
When launching a virtual Android device from the debug view, the debug console shows the following message for a few minutes:
Using  d:\PROJECTS\NS<project>\platforms\android\build\outputs\apk<project>-debug.apk  

and then it errs with:

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:550:26)
Sending exception report (press Ctrl+C to stop)...
Command failed: The debug process exited unexpectedly code:0
Closing debug connection

I have a virtual device already opened (or else I will get an error message right away). I tried different AVDs, but not an actual device. It is perhaps another breaking change in VS Code (I think the extension support 0.10.10)

**Comment by aslabs** [comment]
same here

**Comment by pkoleva** [comment]
Hey @faustinoribeiro @aslabs,

With the latest versions of our extension and the CLI do you still reproduce the issue each time? I couldn't reproduce it on my machine and I'm using NS extension 0.7.0 and CLI 3.0.1 with VS Code 1.12.2.

**Comment by pkoleva** [comment]
Closing this issue due to inactivity
