### ISSUE TITLE
NativeScript 2.30 Error: connect ECONNREFUSED 127.0.0.1:18181

### ISSUE THREAD

**Issue by ownleviathan** [NativeScript/nativescript-vscode-extension#80]
Hi
After update the new version (2.3.0) and type this command: 
tns livesync ios --watch --emulator

shows me the following error:

Applying changes...
{ Error: connect ECONNREFUSED 127.0.0.1:18181
    at Object.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at /usr/local/lib/node_modules/nativescript/lib/services/livesync/ios-device-livesync-service.js:45:150
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/livesync/ios-device-livesync-service.js:87:45
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/livesync/platform-livesync-service-base.js:84:130
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/livesync/platform-livesync-service-base.js:177:81
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:257:28
    at arrayMap (/usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:574:23)
    at Function.map (/usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:8851:14)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:254:29
    - - - - -
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 18181 }

How can I fix this? Thanks

**Comment by ivanbuhov** [comment]
@ownleviathan The VS Code debugger is not expected to reattach itself after livesync.  If you are running `tns livesync ios --watch --emulator` you have to manually detach and attach the VS Code debugger after every sync operation. Our future plans for the `Sync on iOS/Android` commands are to enable [automatic attach/detach by default](https://github.com/NativeScript/nativescript-vscode-extension/issues/78).
